// <auto-generated />
using BobDeathmic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BobDeathmic.Migrations
{
    [DbContext(typeof(BobCoreDBContext))]
    [Migration("20180630075734_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("BobDeathmic.Models.ExternalAuthData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Platform");

                    b.Property<string>("Token");

                    b.HasKey("ID");

                    b.ToTable("AuthData");
                });
#pragma warning restore 612, 618
        }
    }
}
